# Generated by Django 4.2.30 on 2026-05-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('task_codes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('human_overrode_assignment', models.BooleanField(default=False)),
                ('final_assignment', models.CharField(max_length=100)),
                ('ai_was_correct', models.BooleanField(null=True)),
                ('override_note', models.TextField(blank=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='tasks.task')),
            ],
        ),
    ]
