# Generated by Django 4.2.30 on 2026-05-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_digestreport_alter_task_status_taskoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmessage',
            name='recipient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
