# Generated by Django 4.2.30 on 2026-05-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_generatedmessage_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clarification_note',
            field=models.TextField(blank=True),
        ),
    ]
